.gitignore
examples/calendar_contrib/README.md
examples/calendar_contrib/example.md
examples/calendar_contrib/lookatmecontrib/calendar.py
examples/tour.md
lookatme/__main__.py
lookatme/contrib/__init__.py
lookatme/contrib/terminal.py
lookatme/exceptions.py
lookatme/pres.py
lookatme/render/markdown_block.py
lookatme/schemas.py
lookatme/tui.py

Adds support for contrib extensions

---

lookatme/contrib/terminal.py
lookatme/render/pygments.py
lookatme/tui.py

Adds pygments and Urwid pygments renderer caching

---

lookatme/pres.py

Fixes style override from command-line option

---

README.md
lookatme/tui.py

Updated the readme

---

lookatme/utils.py

Fixed the header styles

---

lookatme/parser.py
lookatme/render/markdown_block.py
lookatme/render/markdown_inline.py
lookatme/schemas.py
lookatme/tui.py
lookatme/utils.py
lookatme/widgets/table.py
tests/test_markdown.py
tests/test_parse.py
tests/test_schemas.py
tests/test_table.py
tests/utils.py
tox.ini

fixes #3 
Fixes a lot of things discovered while writing unit tests. Took a while to figure out a good way to test the markdown rendering.

Adds unit tests

---

lookatme/render/markdown_block.py
lookatme/render/pygments.py
tests/test_markdown.py

UrwidFormatter pygments token handling is now fixed

---

setup.py

Updates setup.py to use the README as the description

---

lookatme/render/pygments.py

Gracefully handle invalid languages in code blocks

---

setup.py

Enforces python3 only

---

lookatme/render/markdown_inline.py

inline markdown rendering functions are now overrideable by extensions

---

lookatme/render/pygments.py
tests/test_markdown.py

Fixes empty code blocks

---

lookatme/render/markdown_block.py
tests/test_markdown.py

Fixes newline in lists

---

lookatme/__main__.py
tests/test_cli.py

Added --version flag

---

lookatme/__main__.py
lookatme/tui.py
tests/test_cli.py

Added tests, better error handling

---

lookatme/tui.py

Set global urwid encoding to utf8

---

lookatme/tui.py
presentations/san_diego_python_meetup/2019-12-20.md
presentations/san_diego_python_meetup/source/minimal_flask.py

Fixes incorrect keypress handling

---

docs/source/builtin_extensions/terminal.rst
lookatme/contrib/terminal.py
lookatme/pres.py
lookatme/render/markdown_block.py
lookatme/utils.py

Adds `terminal-ex` mode

---

README.md
docs/source/getting_started.rst
docs/source/style_precendence.rst
lookatme/__main__.py
lookatme/parser.py
lookatme/pres.py
lookatme/render/markdown_block.py
lookatme/schemas.py
lookatme/themes/light.py
tests/test_markdown.py
tests/utils.py

Adds `--single|--one` options and renders hrules

---

docs/source/conf.py
lookatme/tui.py
tox.ini

Root urwid widget is now overridable by extensions

---

lookatme/render/markdown_block.py
lookatme/utils.py
lookatme/widgets/table.py

Changes inline render functions to support widget return values

---

lookatme/contrib/file_loader.py
lookatme/contrib/terminal.py
lookatme/schemas.py
requirements.test.txt
requirements.txt
tests/test_schemas.py
tox.ini

This PR fixes the broken unit tests.
The problem was due to API-breaking changes within marshmallow minor versions. I've updated the marshmallow dependency version and fixed the marshmallow schema definitions (and tests).

See #126 - Fixes unit tests

---

.github/workflows/testing.yml
bin/_utils.sh
bin/ci
lookatme/__main__.py
lookatme/config.py
lookatme/contrib/__init__.py
lookatme/contrib/file_loader.py
lookatme/contrib/terminal.py
lookatme/exceptions.py
lookatme/parser.py
lookatme/pres.py
lookatme/render/markdown_block.py
lookatme/render/markdown_inline.py
lookatme/render/pygments.py
lookatme/schemas.py
lookatme/slide.py
lookatme/themes/__init__.py
lookatme/themes/light.py
lookatme/tui.py
lookatme/utils.py
lookatme/widgets/clickable_text.py
lookatme/widgets/table.py
tests/test_cli.py
tests/test_contrib.py
tests/test_file_loader.py
tests/test_markdown.py
tests/test_parse.py
tests/test_schemas.py
tests/test_table.py
tests/utils.py

See #143 - Fix all follow-up issues to enabling flake8, pyright, isort

#143 Fix issues from linting

---

lookatme/parser.py
lookatme/pres.py
lookatme/schemas.py
lookatme/themes/dark.py
tests/test_cli.py

Fixes the style and theme issues described in #123

Fixes style and theme issues.

---

README.md
docs/source/getting_started.rst
docs/source/index.rst
examples/tour.md
tests/test_parse.py

Updates documentation and README to include progressive slides

---

.github/workflows/pypi_publish.yml
README.md
bin/fill_placeholders
docs/source/getting_started.rst
lookatme/__main__.py
lookatme/config.py
lookatme/parser.py
lookatme/pres.py
lookatme/render/markdown_block.py
lookatme/render/markdown_inline.py
lookatme/themes/__init__.py
lookatme/tui.py
lookatme/tutorial.py
lookatme/utils.py
setup.py
tests/test_contrib.py
tests/test_tutorial.py

Really happy with how this is turning out!
Fixes #169

Adds tutorials!

---

CHANGELOG.md

Really need to automate this...

Version bump to 2.5.0

---

.github/workflows/testing.yml
bin/ci
lookatme/__main__.py
lookatme/config.py
lookatme/parser.py
lookatme/render/context.py
lookatme/render/markdown_block.py
lookatme/render/markdown_inline.py
lookatme/schemas.py
lookatme/themes/__init__.py
lookatme/tutorial.py
tests/test_contrib.py
tests/test_file_loader.py
tests/test_markdown.py
tests/test_parse.py
tests/test_slides.py
tests/test_table.py
tests/test_tutorial.py
tests/utils.py
tox.ini

fixes #163 
Also adds style schemas for:
* emphasis
* strong_emphasis
* strikethrough

3.0 - Adds/fixes unit tests

---

lookatme/render/context.py
lookatme/tui.py

* Adds a clone method to Context that performs a limited clone.
* Uses a cloned version of the context for the bg render thread.

Uses a cloned context for the background render thread

---

lookatme/render/markdown_block.py
lookatme/tutorial.py
tests/test_tutorial.py

Fixes tutor tag replacement/extraction

---

lookatme/log.py
lookatme/pres.py
lookatme/render/markdown_inline.py
lookatme/schemas.py
lookatme/tui.py
lookatme/tutorial.py
lookatme/widgets/scroll_monitor.py
lookatme/widgets/scrollbar.py
tests/test_slides.py

This PR adds a scrollbar to the slide contents when needed.
